Algoritmo "AtividadeResolva"

Var

   A:inteiro
   B:inteiro
   x:inteiro

Inicio

   A <- 10
   B <- 20

   escreval("Primeiros Valores")
   escreval("Valor de A é:",A)
   escreval("Valor de B é:",B)


   escreval("")
   escreval("")

   escreval("Trocando os Valores")

   escreval("")
   escreval("")


   x <- a
   a <- b
   b <- x


   escreval("Valores Trocados")
   escreval("Valor de A é:",A)
   escreval("Valor de B é:",B)



Fimalgoritmo