Algoritmo "celsius-fahrenheit"

Var

   C:real
   F:real


Inicio
   escreval("Este é um conversor de temperatura. (F° para C°)")
   escreval("")

   escreval("Informe sua temperatura em graus celsius (F°)")
   leia(F)

   C <- 5/9 * (F - 32)
   
   escreval("")
   escreval("------------------------------------------------------")
   escreval("")
   
   escreval ("Pronto!!",F," graus Fahrenheit são", C," graus Celsius.")



Fimalgoritmo